### ISSUE TITLE
✨`Member`, `RefreshToken`, `Notification` 도메인 구현

### ISSUE THREAD

**Issue by dltjdn** [Beachcombing/beachcombing-backend#15]
## 📌 Description
- Member 와 관련된 도메인을 생성한다

## 📝 To-do
- [x]  Member domain 수정
- [x]  TokenPair -> RefreshToken 으로 변경 및 필드 수정
- [x]  Notification domain 생성
- [x] BaseEntity 생성
