### ISSUE TITLE
✨`Record`, `Beach`, `Trashcan` 도메인 구현

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beachcombing/beachcombing-backend#17]
## 📌 Description
- 청소 기록과 지도에 찍힐 정보들과 관련된 도메인을 구현한다.

## 📝 To-do
- [x] Record 도메인 구현
- [x] Beach 도메인 구현
- [x] Trashcan 도메인 구현
