### ISSUE TITLE
✨ Record 관련 API 구현

### ISSUE THREAD

**Issue by dltjdn** [Beachcombing/beachcombing-backend#29]
## 📌 Description
- Record 와 관련된 API 를 구현한다

## 📝 To-do
- [x] 청소 기록하기 API 구현
- [x] 전체 청소 기록 목록 조회 API 구현 
- [x] (지도) 청소한 해변 마커 조회 API 구현 
- [x] (지도) 특정 위치 청소 기록 목록 조회 API 구현
