### ISSUE TITLE
✨ 포인트받기 및 알림 목록 조회 API 구현

### ISSUE THREAD

**Issue by dltjdn** [Beachcombing/beachcombing-backend#36]
## 📌 Description
- 포인트받기 및 알림 목록 조회 API를 구현한다

## 📝 To-do
- [x] 이벤트 관련 코드 구현
- [x] 포인트 받기 API 구현
- [x] 알림 목록 조회 API 구현
