### ISSUE TITLE
✨ 쓰레기통 관련 api 구현

### ISSUE THREAD

**Issue by ChooSeoyeon** [Beachcombing/beachcombing-backend#54]
## 📌 Description
- 쓰레기통 관련한 api들을 구현한다.

## 📝 To-do
- [x] 홈 / 쓰레기통 신고 api
- [x] 홈 / (지도) 쓰레기통 위치 조회 api
- [x] 관리자 / 쓰레기통 인증 api
- [x] 관리자 / 쓰레기통 인증 목록 조회 api
