### ISSUE TITLE
✨ JWT 토큰 서버 구축 및 관련 개발 환경 조성.

### ISSUE THREAD

**Issue by dltjdn** [Beachcombing/beachcombing-backend#7]
## 📌 Description
- JWT 토큰 서버를 구축하고 관련한 개발 환경을 조성한다.

## 📝 To-do
- [ ] JWT 토큰 서버 구축
- [ ] 토큰 서버 테스트용 API 구현
    - [ ] 회원 정보 조회 API
    - [ ] 로그인 API
    - [ ] 회원가입 API
